package com.sentinel.eventstore.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.util.UUID;

/**
 * Alert — Represents a critical security violation that requires analyst attention.
 * Automatically generated by the Event Store when a BLOCK decision is recorded.
 */
@Entity
@Table(name = "alerts")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Alert {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private UUID id;

    private UUID sessionId;
    private String userId;
    private String endpoint;
    private String reason; // Rule ID or condition that triggered the block
    private double riskScore;
    private long timestampNs;
    
    @Enumerated(EnumType.STRING)
    private AlertStatus status; // OPEN, INVESTIGATING, RESOLVED, FALSE_POSITIVE

    public enum AlertStatus {
        OPEN, INVESTIGATING, RESOLVED, FALSE_POSITIVE
    }
}
