import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
    stages: [
        { duration: '10s', target: 50 }, // Ramp up
        { duration: '30s', target: 200 }, // Sustained load
        { duration: '10s', target: 0 }, // Ramp down
    ],
    thresholds: {
        http_req_duration: ['p(99)<=15'], // 99% of requests must complete below 15ms
    },
};

export default function () {
    // Requires TOKEN to be completely injected
    const token = __ENV.TOKEN;
    
    if (!token) {
        console.error("Please export TOKEN environment variable generated by generate_test_token.py");
    }

    const params = {
        headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json',
        },
    };

    // Calling the proxied backend user-service 
    let res = http.get('http://localhost:8080/api/users/profile', params);

    check(res, {
        'status is 200': (r) => r.status === 200,
        'latency < 15ms': (r) => r.timings.duration < 15,
    });

    sleep(0.01);
}
